### ISSUE TITLE
add feature to download xml getcapabilities in csv_generator_for_wmts_tests.py

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/scripts#16]
As discussed with @simboss:
using the script csv_generator_for_wmts_tests.py (performance_tests\WMTS) it is necessary to have the capabilities in a file named
"wmts-getcapabilities.xml".
I think useful to add an option to download directly the getcapabilities (asking for the base url of GeoServer), instead of dowload it manually.
What do you think @randomorder?

**Comment by randomorder** [comment]
I agree

**Comment by chpicone** [comment]
Ok I've updated the script in this way.
The script check if the xml file (wmts-getcapabilities.xml) already exists in the cwd.
If yes use it, otherwise asks the user to provide geoserver URL and download the capababilities in the cwd with name wmts-getcapabilities.xml

**Comment by chpicone** [comment]
@randomorder please take a quick look.

**Comment by randomorder** [comment]
thanks @chpicone
